stackabletech/airflow-operator

- CHANGELOG.md
- deploy/helm/airflow-operator/crds/crds.yaml
- rust/crd/src/lib.rs
cherry picked from commit 43089237dc032cb254f0c738b2574fa4e74125a9
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
> Add missing crd defaults to 23.4

- CHANGELOG.md
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
- docs/modules/airflow/pages/usage-guide/security.adoc
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- rust/crd/src/authentication.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/config.rs
- rust/operator-binary/src/main.rs
- tests/templates/kuttl/ldap/06-install-airflow-cluster.yaml.j2
fixes https://github.com/stackabletech/airflow-operator/issues/298
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/94/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
> Consolidate authentication config in CRD

- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Fix warnings introduced by the Rust 1.71 upgrade

- CHANGELOG.md
- Cargo.lock
- docs/modules/airflow/examples/example-airflow-dags-configmap.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/examples/example-airflow-incluster.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml.j2
- docs/modules/airflow/pages/usage-guide/security.adoc
- rust/crd/Cargo.toml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/config.rs
- tests/templates/kuttl/cluster-operation/03-install-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/10-pause-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/30-restart-airflow.yaml.j2
- tests/templates/kuttl/ldap/06-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/logging/04-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-configmap/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-gitsync/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/orphaned-resources/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/resources/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/smoke/40-install-airflow-cluster.yaml.j2
- tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Default stackableVersion to operator version

- Cargo.lock
- Cargo.toml
- deploy/helm/airflow-operator/crds/crds.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Switch to workspace dependencies

- docs/modules/airflow/pages/getting_started/index.adoc
- docs/modules/airflow/pages/getting_started/installation.adoc
- docs/modules/airflow/pages/index.adoc
- docs/modules/airflow/pages/prerequisites.adoc
- docs/modules/airflow/pages/required-external-components.adoc
- docs/modules/airflow/partials/hardware-requirements.adoc
- docs/modules/airflow/partials/nav.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: added page about external dependencies

- rust/operator-binary/src/airflow_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
> refactor: Use operator-rs Duration

- Cargo.lock
- Cargo.toml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/airflow_controller.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- CHANGELOG.md
- Cargo.toml
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/modules/airflow/pages/usage-guide/operations/graceful-shutdown.adoc
- rust/crd/src/git_sync.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/operations/graceful_shutdown.rs
- rust/operator-binary/src/operations/mod.rs
- tests/templates/kuttl/smoke/40-assert.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Support graceful shutdown

- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
- docs/modules/airflow/pages/getting_started/installation.adoc
- docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```
> docs: Add listener-operator where missing

- tests/templates/kuttl/ldap/06-install-airflow-cluster.yaml.j2
test run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/111/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Stabilize LDAP integration tests due to timeouts.

- tests/templates/kuttl/cluster-operation/03-install-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/10-pause-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/30-restart-airflow.yaml.j2
- tests/templates/kuttl/ldap/06-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/logging/04-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-configmap/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-gitsync/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/orphaned-resources/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/resources/03-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/smoke/40-install-airflow-cluster.yaml.j2
Part of https://github.com/stackabletech/issues/issues/481
> feat(test): pull policy IfNotPresent for Airflow clusters

- CHANGELOG.md
- deploy/helm/airflow-operator/templates/_helpers.tpl
- deploy/helm/airflow-operator/templates/deployment.yaml
- deploy/helm/airflow-operator/templates/roles.yaml
- deploy/helm/airflow-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
- feat(helm): support labels in values.yaml
- doc: changelog
> feat(helm): support labels in values.yaml

- deploy/helm/airflow-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add Stackable vendor label to default values.yaml

- CHANGELOG.md
- docs/modules/airflow/examples/example-airflow-secret.yaml
- docs/modules/airflow/examples/getting_started/code/airflow-credentials.yaml
- examples/simple-airflow-cluster-dags-cmap.yaml
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- examples/simple-airflow-cluster.yaml
- rust/operator-binary/src/env_vars.rs
- tests/templates/kuttl/ldap/60-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-configmap/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/smoke/40-install-airflow-cluster.yaml.j2
Fixes https://github.com/stackabletech/airflow-operator/issues/424
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Remove requirement of celery configs when using kubernetes executors 

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- tests/templates/kuttl/logging/41-copy-prepared-logs.yaml
- tests/templates/kuttl/logging/airflow-vector-aggregator-values.yaml.j2
- tests/templates/kuttl/logging/prepared-logs.py.json
Add prepared logs to the logging test containing invalid log events
Tests stackabletech/operator-rs#802
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add prepared logs to the logging test

- tests/templates/kuttl/cluster-operation/08-install-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/10-pause-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/30-restart-airflow.yaml.j2
- tests/templates/kuttl/ldap/60-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/logging/41-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-configmap/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/orphaned-resources/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/resources/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/smoke/40-install-airflow-cluster.yaml.j2
- tests/test-definition.yaml
- **feat(test): custom images**
- **update test-definition.yaml**
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test custom images

- tests/templates/kuttl/logging/30-install-airflow-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use Vector Helm chart version 0.34.0 in the logging test

- docs/modules/airflow/examples/example-spark-dag.py
- docs/modules/airflow/examples/example_spark_kubernetes_operator.py
- docs/modules/airflow/examples/example_spark_kubernetes_sensor.py
- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
- docs/modules/airflow/examples/getting_started/code/install_output.txt
- docs/modules/airflow/examples/getting_started/code/install_output.txt.j2
- docs/modules/airflow/pages/getting_started/installation.adoc
- tests/templates/kuttl/commons/health.py
- tests/templates/kuttl/commons/metrics.py
- tests/templates/kuttl/logging/test_log_aggregation.py
- tests/templates/kuttl/mount-dags-gitsync/dag_metrics.py
- tests/templates/kuttl/mount-dags-gitsync/dags/pyspark_pi.py
- tests/templates/kuttl/mount-dags-gitsync/dags/stackable/spark_kubernetes_operator.py
- tests/templates/kuttl/mount-dags-gitsync/dags/stackable/spark_kubernetes_sensor.py
> docs(getting-started): update stackablectl op install output

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
- tests/templates/kuttl/cluster-operation/30-assert.yaml
- tests/templates/kuttl/commons/health.py
- tests/templates/kuttl/commons/metrics.py
- tests/templates/kuttl/logging/41-assert.yaml.j2
- tests/templates/kuttl/logging/41-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/logging/51-assert.yaml
- tests/templates/kuttl/logging/51-health-check.yaml
- tests/templates/kuttl/logging/52-assert.yaml
- tests/templates/kuttl/logging/52-install-metrics-script.yaml
- tests/templates/kuttl/logging/airflow-vector-aggregator-values.yaml.j2
- tests/test-definition.yaml
Prevent double logging of the airflow container logs
Both executors are now tested in the logging test.
Fixes #473 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Prevent double logging of the airflow container logs

- docs/modules/airflow/pages/usage-guide/logging.adoc
- docs/modules/airflow/pages/usage-guide/monitoring.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/pages/usage-guide/storage-resources.adoc
- docs/modules/airflow/pages/usage.adoc
Part of https://github.com/stackabletech/documentation/issues/637
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: remove home module from refs (stackabletech/documentation#637)

- docs/modules/airflow/pages/usage-guide/mounting-dags.adoc
> chore: fix small typo

- deploy/helm/airflow-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(helm): use same scc as olm

- docs/modules/airflow/examples/example-pyspark-pi.yaml
part of https://github.com/stackabletech/docker-images/issues/838
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: update spark example version

- docs/modules/airflow/pages/getting_started/first_steps.adoc
- docs/modules/airflow/pages/getting_started/index.adoc
- docs/modules/airflow/pages/getting_started/installation.adoc
- docs/modules/airflow/pages/index.adoc
- docs/modules/airflow/pages/required-external-components.adoc
- docs/modules/airflow/pages/usage-guide/applying-custom-resources.adoc
- docs/modules/airflow/pages/usage-guide/index.adoc
- docs/modules/airflow/pages/usage-guide/listenerclass.adoc
- docs/modules/airflow/pages/usage-guide/logging.adoc
- docs/modules/airflow/pages/usage-guide/monitoring.adoc
- docs/modules/airflow/pages/usage-guide/mounting-dags.adoc
- docs/modules/airflow/pages/usage-guide/overrides.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/pages/usage-guide/storage-resources.adoc
- docs/modules/airflow/pages/usage-guide/using-kubernetes-executors.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add descriptions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/airflow-operator/crds/crds.yaml
- rust/operator-binary/src/config.rs
- rust/operator-binary/src/controller_commons.rs
- rust/operator-binary/src/util.rs
part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump op-rs

- docs/modules/airflow/pages/getting_started/first_steps.adoc
- docs/modules/airflow/pages/getting_started/index.adoc
- docs/modules/airflow/pages/getting_started/installation.adoc
- docs/modules/airflow/pages/index.adoc
- docs/modules/airflow/pages/reference/commandline-parameters.adoc
- docs/modules/airflow/pages/reference/environment-variables.adoc
- docs/modules/airflow/pages/required-external-components.adoc
- docs/modules/airflow/pages/usage-guide/applying-custom-resources.adoc
- docs/modules/airflow/pages/usage-guide/logging.adoc
- docs/modules/airflow/pages/usage-guide/mounting-dags.adoc
- docs/modules/airflow/pages/usage-guide/operations/graceful-shutdown.adoc
- docs/modules/airflow/pages/usage-guide/operations/index.adoc
- docs/modules/airflow/pages/usage-guide/operations/pod-disruptions.adoc
- docs/modules/airflow/pages/usage-guide/operations/pod-placement.adoc
- docs/modules/airflow/pages/usage-guide/overrides.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/pages/usage-guide/using-kubernetes-executors.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: pod overrides and other improvements

- tests/templates/kuttl/overrides/10-install-airflow.yaml.j2
- tests/templates/kuttl/overrides/20-install-airflow2.yaml.j2
Fixes usage of custom images in the overrides test. This test would aways fail with a custom image.
> Fixes usage of custom images in the overrides test

- docs/modules/airflow/examples/example_spark_kubernetes_sensor.py
Behaviour changed in the airflow-operator so the failure states need to be adjusted.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Remove unknown from failure states in example file

- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/install_output.txt
Part of https://github.com/stackabletech/issues/issues/647.
> docs: Update release in getting_started

- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/airflow-operator/pull/542.
> chore(getting_started): Replace templating instructions with make

- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: remove unused env var

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
PR to fix unmaintained crate cargo deny errors
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump stackable-operator version and cargo update

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/airflow-operator/templates/roles.yaml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```
> chore: Update to operator-rs 0.84.0

- tests/templates/kuttl/logging/30-install-airflow-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update Vector to 0.43.1 in integration tests

- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-logging.yaml
This was a copy&paste oversight.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Fix remote logging env var names

- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-logging.yaml
- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-xcom.yaml
- docs/modules/airflow/pages/usage-guide/using-kubernetes-executors.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Document how to store xCom objects in S3

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/airflow-operator/Chart.yaml
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.3.0

- CHANGELOG.md
- tests/templates/kuttl/opa/20-install-opa.yaml.j2
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
> test: Bump OPA to 1.4.2

- tests/templates/kuttl/logging/30-install-airflow-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
> chore: bump vector chart to 0.43.0

- CHANGELOG.md
- deploy/helm/airflow-operator/templates/roles.yaml
> fix: Backport Add RBAC permission to patch events

- tests/templates/kuttl/overrides/21-assert.yaml
```
--- PASS: kuttl (146.94s)
--- PASS: kuttl/harness/overrides_airflow-latest-3.0.1_openshift-false (146.63s)
PASS
```
> fix: overrides test
