stackabletech/airflow-operator

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
Fixes https://github.com/stackabletech/airflow-operator/issues/146
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Rename Service port name from `airflow` to `http`

- tests/templates/kuttl/logging/airflow-vector-aggregator-values.yaml.j2
In addition to https://github.com/stackabletech/airflow-operator/pull/322:
One of the nightly tests was failing, because it checked the InitDb logs, which are now part of the scheduler log and not their own log anymore. I removed this part of the test.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Removed check for InitDb logs

- deploy/helm/airflow-operator/templates/roles.yaml
- docs/modules/airflow/pages/index.adoc
Removed AirflowDB references in docs and RBAC config.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Removed AirflowDB references in docs and RBAC config

- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/product_logging.rs
- tests/templates/kuttl/logging/03-install-airflow-vector-aggregator.yaml
* Upgrade Vector to version 0.33.0 in the tests, which is provided by the Vector Helm chart version 0.26.0.
* Fix Clippy warnings
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Upgrade Vector to version 0.33.0 in the tests

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
See https://github.com/stackabletech/airflow-operator/issues/371.
The `envOverrides` entries are added to the config-map for the `kubernetesExecutor` pod template by iterating over a `HashMap`: this leads to a unpredictable order and unnecessary restarts of airflow components. The `HashMap` is converted to a `BTreeMap` to avoid this happening.
:green_circle: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/121/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Fix pod template envvars

- docs/modules/airflow/pages/usage-guide/logging.adoc
- docs/modules/airflow/pages/usage-guide/storage-resources.adoc
- docs/modules/airflow/pages/usage-guide/using-kubernetes-executors.adoc
- docs/modules/airflow/partials/nav.adoc
Fixes https://github.com/stackabletech/airflow-operator/issues/370 (all `grep -r 'workers:'` findings fixed)
Previously it was only at https://docs.stackable.tech/home/stable/airflow/ and IMHO hard to find
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Add usage guide on Kubernetes executors

- CHANGELOG.md
- rust/crd/src/git_sync.rs
- rust/operator-binary/src/airflow_controller.rs
Fixes https://github.com/stackabletech/airflow-operator/issues/379. Run git-sync as one-time call in an init container for k8s-mode.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Run git-sync as one-time call with KubernetesExecutor

- CHANGELOG.md
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/modules/airflow/examples/example-airflow-dags-configmap.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/examples/example-airflow-incluster.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml
- docs/modules/airflow/pages/usage-guide/mounting-dags.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/partials/supported-versions.adoc
- examples/simple-airflow-cluster-dags-cmap.yaml
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- examples/simple-airflow-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/git_sync.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/airflow_controller.rs
- tests/test-definition.yaml
- add version 2.7.3, 2.8.1
- remove version 2.6.1, 2.7.1
- bump git-sync to 4.2.1
fixes https://github.com/stackabletech/airflow-operator/issues/363, https://github.com/stackabletech/airflow-operator/issues/362
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Support version 2.7.3, 2.8.1, remove 2.6.1, 2.7.1

- CHANGELOG.md
- rust/crd/src/lib.rs
- rust/operator-binary/src/airflow_controller.rs
- tests/release.yaml
- tests/templates/kuttl/ldap/03-install-openldap.yaml.j2
The `webserver` pods don't start up in timely manner and are stuck in crash loop.
Raise memory request and liveness timeouts.
Tests are successful on OpenShift 4.15:
```
--- PASS: kuttl (918.99s)
--- PASS: kuttl/harness/smoke_airflow-2.8.1_openshift-true_executor-kubernetes (290.13s)
--- PASS: kuttl/harness/cluster-operation_airflow-latest-2.8.1_openshift-true (317.03s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-2.8.1_openshift-true_executor-kubernetes (179.60s)
--- PASS: kuttl/harness/ldap_airflow-latest-2.8.1_ldap-authentication-server-verification-tls_openshift-true_executor-kubernetes (196.86s)
--- PASS: kuttl/harness/orphaned-resources_airflow-latest-2.8.1_openshift-true (163.28s)
--- PASS: …
```
> fix(webserver): raise liveness probe timeouts

- CHANGELOG.md
- deploy/helm/airflow-operator/templates/roles.yaml
Add missing permission for airflow to retrieve temporary pod logs.
Before, in Airflow, you would see this while a task is running:
```
sparkapp-dag-spark-pi-monitor-e2ndngqe
*** Attempting to fetch logs from pod sparkapp-dag-spark-pi-monitor-e2ndngqe through kube API
*** Reading from k8s pod logs failed: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76bcd5e8-57c5-4585-9e75-17054c661530', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 18 Mar 2024 09:16:47 GMT', 'Content-Length': '391'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"sparkapp-dag-spark-pi-monitor-e2ndngqe\\" is forbidden: User …
```
> fix(manifests): add missing permission for airflow to retrieve temporary pod logs

- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
In the PR-merge for #404 the PR branch was not reverted to `main` and so the integration test tried to git-sync from a non-existent location. This fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: revert branch reference to main

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/env_vars.rs
- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
- tests/templates/kuttl/mount-dags-gitsync/31-assert.yaml.j2
See https://github.com/orgs/stackabletech/discussions/49.
Also part of https://github.com/stackabletech/issues/issues/548.
This is to enable [SSH-usage](https://github.com/kubernetes/git-sync/blob/master/docs/ssh.md) using volumes/volumeMounts/envOverrides (which should be available anyway): incorporating this into the CRD is not part of this ticket.
CI tests :green_circle:  https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/136/
OKD :green_circle:
```
--- PASS: kuttl (806.00s)
--- PASS: kuttl/harness/smoke_airflow-2.8.1_openshift-true_executor-kubernetes (215.72s)
--- PASS: kuttl/harness/cluster-operation_airflow-latest-2.8.1_openshift-true (269.89s)
--- PASS: kuttl/harness/logging_airflow-2.8.1_openshift-true …
```
> pass volumes/volume-mounts and env-vars through to gitsync containers

- docs/modules/airflow/pages/usage-guide/logging.adoc
- docs/modules/airflow/pages/usage-guide/monitoring.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/pages/usage-guide/storage-resources.adoc
Part of https://github.com/stackabletech/documentation/issues/637
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: remove home module from refs (stackabletech/documentation#637)

- tests/templates/kuttl/smoke/41-assert.yaml
Kuttl hard codes `sh -c`, instead of allowing alternative shells to be used.
For now, we need to drop the `-o pipefail` option.
See: https://github.com/kudobuilder/kuttl/issues/557
> [!NOTE]
> For zsh users, `sh` appears to just alias zsh, so locally `set -euo pipfail` worked fine.
> test(kuttl): Remove the -o pipefail bash option

- CHANGELOG.md
- docs/modules/airflow/examples/example-airflow-dags-configmap.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/examples/example-airflow-incluster.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/partials/supported-versions.adoc
- examples/simple-airflow-cluster-dags-cmap.yaml
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- examples/simple-airflow-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/git_sync.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/airflow_controller.rs
- tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
- Add `2.9.3`
- Deprecate `2.9.2`
- Remove `2.6.x` and `2.8.x`
> chore: Add airflow 2.9.3, deprecate 2.9.2, remove 2.6.x and 2.8.x

- CHANGELOG.md
- docs/modules/airflow/partials/supported-versions.adoc
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/847
Add Airflow 2.10.2 to tests and docs (except getting_started).
> [!NOTE]
> @sbernauer and I discussed whether the experimental version should be listed as latest, or even included in the general test run. We decided on adding it, and if it proves problematic, we can remove it again.
```[tasklist]
```
```[tasklist]
```
> feat: Add Airflow 2.10.2 to tests

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/main.rs
Part of: https://github.com/stackabletech/issues/issues/211
~~**Actually** it still stops reconciling if an authentication class is invalid. Not sure if that check can be removed now.~~
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: don't stop the reconciliation if one cluster is invalid

- docs/modules/airflow/pages/reference/environment-variables.adoc
Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs.
part of https://github.com/stackabletech/issues/issues/668
> Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/airflow_controller.rs
Some minor changes needed to remove dependency on now private fn in op-rs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Patch op-rs version to use one that fixes SUP-148.

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/config.rs
Part of https://github.com/stackabletech/operator-rs/pull/910
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Construction of OIDC endpoint when rootPath has a trailing slash

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- Makefile
- crate-hashes.json
- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/config.rs
Add the following PRs to the release 24.11:
* #542 
* #543 
* #545 
* #547
> Update release branch

- CHANGELOG.md
- rust/crd/src/lib.rs
- tests/templates/kuttl/smoke/40-assert.yaml.j2
Part of: https://github.com/stackabletech/issues/issues/527
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: run containerdebug in the background

- tests/templates/kuttl/cluster-operation/02-install-postgresql.yaml
- tests/templates/kuttl/ldap/05-install-postgresql.yaml
- tests/templates/kuttl/logging/05-install-postgresql.yaml
- tests/templates/kuttl/mount-dags-configmap/05-install-postgresql.yaml
- tests/templates/kuttl/mount-dags-gitsync/03-install-postgresql.yaml
- tests/templates/kuttl/oidc/10-install-postgresql.yaml
- tests/templates/kuttl/orphaned-resources/05-install-postgresql.yaml
- tests/templates/kuttl/overrides/05-install-postgresql.yaml
- tests/templates/kuttl/resources/05-install-postgresql.yaml
- tests/templates/kuttl/smoke/10-install-postgresql.yaml
Bump postgresql helm chart version to most recent one.
Installation of version 12.5.6 seems to fail due to the chart being missing or rate limits being enforced by bitnami, see https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/15/artifact/target/test-output.log
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump postgresql helm chart version in tests

- tests/templates/kuttl/opa/31-opa-rules.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/998
Tests:
```
--- PASS: kuttl (222.93s)
--- PASS: kuttl/harness/opa_airflow-2.10.2_opa-latest-1.0.1_openshift-false (222.91s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump opa to 1.0.1

- CHANGELOG.md
- docs/modules/airflow/examples/example-airflow-dags-configmap.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/examples/example-airflow-incluster.yaml
- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-logging.yaml
- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-xcom.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/partials/supported-versions.adoc
- examples/simple-airflow-cluster-dags-cmap.yaml
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- examples/simple-airflow-cluster.yaml
- rust/operator-binary/src/crd/affinity.rs
- rust/operator-binary/src/crd/git_sync.rs
- rust/operator-binary/src/crd/mod.rs
- tests/test-definition.yaml
- Add: 2.10.4
- Remove: 2.9.2, 2.10.2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Update test and doc versions

- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
- docs/modules/airflow/pages/getting_started/installation.adoc
- docs/templating_vars.yaml
Part of <https://github.com/stackabletech/issues/issues/697>
This PR bumps the following charts:
- `postgresql` to 16.5.0
- `redis` to 20.11.3
```shell
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
```
> chore(docs): Update getting-started script pre-25.3.0

- CHANGELOG.md
- Cargo.lock
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/pages/usage-guide/mounting-dags.adoc
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/crd/git_sync.rs
- rust/operator-binary/src/env_vars.rs
- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
If `gitFolder` was missing the stacklet was basically entirely broken.
For changes see `CHANGELOG.md`
For CRD change see `deploy/helm/airflow-operator/crds/crds.yaml`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix!: Rework git-sync CRD to not fail on missing gitFolder

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/main.rs
**Use `Tracing::pre_configured` from stackable-telemetry**
Part of https://github.com/stackabletech/issues/issues/639.
Breaking changes:
- The console log level was set by `AIRFLOW_OPERATOR_LOG`, and is now set by `CONSOLE_LOG`.
- The file log level was set by `AIRFLOW_OPERATOR_LOG`, and is now set by `FILE_LOG`.
- The file log directory was previously changed to `ROLLING_LOGS`, but has been updated to `ROLLING_LOGS_DIR`.
```
--- PASS: kuttl (869.92s)
--- PASS: kuttl/harness/logging_airflow-2.10.4_openshift-false_executor-celery (474.70s)
--- PASS: kuttl/harness/logging_airflow-2.10.4_openshift-false_executor-kubernetes (395.21s)
PASS
```
> feat!: Use `Tracing::pre_configured` from stackable-telemetry

- tests/templates/kuttl/opa/40-install-test-container.yaml.j2
Part of https://github.com/stackabletech/infrastructure/issues/142
Repository references were already updated for this repo with changelog entry already present, new old docker.stackable.tech reference was added after, this PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: update to oci references

- CHANGELOG.md
- tests/templates/kuttl/logging/30-install-airflow-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 in tests
> test: Bump vector to 0.46.1

- CHANGELOG.md
- docs/modules/airflow/examples/example-airflow-dags-configmap.yaml
- docs/modules/airflow/examples/example-airflow-gitsync.yaml
- docs/modules/airflow/examples/example-airflow-incluster.yaml
- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-logging.yaml
- docs/modules/airflow/examples/example-airflow-kubernetes-executor-s3-xcom.yaml
- docs/modules/airflow/examples/getting_started/code/airflow.yaml
- docs/modules/airflow/pages/required-external-components.adoc
- docs/modules/airflow/pages/usage-guide/security.adoc
- docs/modules/airflow/partials/supported-versions.adoc
- examples/simple-airflow-cluster-dags-cmap.yaml
- examples/simple-airflow-cluster-ldap-insecure-tls.yaml
- examples/simple-airflow-cluster-ldap.yaml
- examples/simple-airflow-cluster.yaml
- rust/operator-binary/src/crd/affinity.rs
- rust/operator-binary/src/crd/git_sync.rs
- rust/operator-binary/src/crd/mod.rs
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1074
> test: Add airflow 2.10.5

- rust/operator-binary/src/product_logging.rs
Fix as outcome of https://github.com/stackabletech/airflow-operator/issues/646
This change does not require a changelog entry because the field `propagate` is already set to `True` by default since Airflow 2.4.2 (https://github.com/apache/airflow/blob/2.4.2/airflow/config_templates/airflow_local_settings.py#L120-L137) and setting it explicitly does not change the behavior of the product.
> Fix: proper assignment of Boolean "propagate"

- CHANGELOG.md
- docs/modules/airflow/pages/usage-guide/logging.adoc
- rust/operator-binary/src/product_logging.rs
As an outcome of [#646](https://github.com/stackabletech/airflow-operator/issues/646) I've updated:
- Log level of airflow.task defaults to `INFO`
- Update documentation
> Fix: airflow.task log level default to INFO

- tests/templates/kuttl/mount-dags-gitsync/30-install-airflow-cluster.yaml.j2
```bash
❯ ./scripts/run-tests --test mount-dags-gitsync_airflow-latest-3.0.1_openshift-false_executor-celery --skip-delete
...
--- PASS: kuttl (352.45s)
--- PASS: kuttl/harness/mount-dags-gitsync_airflow-latest-3.0.1_openshift-false_executor-celery (352.43s)
PASS
```
> tests: update access token to dags repository

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/airflow-operator/crds/crds.yaml
- deploy/helm/airflow-operator/templates/roles.yaml
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
> chore: Bump Rust dependencies pre-25.7.0

- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/service.rs
This PR adds `-headless` service to all airflow roles
> Fix: headless svc for all roles as connection requires

- CHANGELOG.md
- deploy/helm/airflow-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
> fix: Add RBAC permission to patch events

- CHANGELOG.md
- docs/modules/airflow/examples/getting_started/code/getting_started.sh
- docs/modules/airflow/examples/getting_started/code/getting_started.sh.j2
Without this, there is a high chance of hitting this error:
```
We have a healthy webserver!
Triggering a DAG run. Enable DAG...
{
"detail": null,
"status": 404,
"title": "Dag with id: 'example_trigger_target_dag' not found",
"type": "https://airflow.apache.org/docs/apache-airflow/2.10.5/stable-rest-api-ref.html#section/Errors/NotFound"
}
Checking DAG result ...
The DAG was not successful. State:  null
```
> fix(getting_started): Add timeout before enabling DAG

- CHANGELOG.md
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/config.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/env_vars.rs
- tests/templates/kuttl/opa/20-assert.yaml
- tests/templates/kuttl/opa/20-install-opa.yaml.j2
- tests/templates/kuttl/opa/30-install-airflow.yaml.j2
Part of https://github.com/stackabletech/airflow-operator/issues/640
> fix: OPA authorization for Airflow 3

- CHANGELOG.md
- deploy/helm/airflow-operator/crds/crds.yaml
- docs/modules/airflow/pages/usage-guide/db-init.adoc
- docs/modules/airflow/partials/nav.adoc
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/crd/mod.rs
- tests/templates/kuttl/cluster-operation/09-assert.yaml
- tests/templates/kuttl/cluster-operation/30-restart-airflow.yaml.j2
- tests/templates/kuttl/cluster-operation/31-assert.yaml
Part of https://github.com/stackabletech/airflow-operator/issues/589
> feat: Add flag for db init routine

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- rust/operator-binary/src/airflow_controller.rs
- rust/operator-binary/src/crd/mod.rs
Fixes https://github.com/stackabletech/airflow-operator/issues/677
> fix: Allow multiple Airflows in the same namespace to use Kubernetes executors

- CHANGELOG.md
- docs/modules/airflow/pages/troubleshooting/index.adoc
- rust/operator-binary/src/env_vars.rs
- tests/templates/kuttl/overrides/10-install-airflow.yaml.j2
- tests/templates/kuttl/overrides/11-assert.yaml
- tests/templates/kuttl/overrides/20-install-airflow2.yaml.j2
- tests/templates/kuttl/overrides/21-assert.yaml
Related to https://github.com/stackabletech/airflow-operator/issues/689
> chore: Update uvicorn to fix worker timeout issue

- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1238
```
--- PASS: kuttl (447.82s)
--- PASS: kuttl/harness/opa_airflow-3.0.1_opa-latest-1.8.0_openshift-false (222.74s)
--- PASS: kuttl/harness/opa_airflow-2.10.4_opa-latest-1.8.0_openshift-false (222.97s)
--- PASS: kuttl/harness/opa_airflow-2.10.5_opa-latest-1.8.0_openshift-false (225.07s)
PASS
```
> chore: Bump opa version for 25.11.0
